// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseID: typeof import('./src/components/strings/BaseID.vue')['default']
    BigNumber: typeof import('./src/components/numbers/BigNumber.vue')['default']
    Column: typeof import('primevue/column')['default']
    CurveText: typeof import('./src/components/CurveText.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    EmoteNumber: typeof import('./src/components/numbers/EmoteNumber.vue')['default']
    EntryGrid: typeof import('./src/components/items/EntryGrid.vue')['default']
    EntryTreeMap: typeof import('./src/components/items/EntryTreeMap.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GearedNumber: typeof import('./src/components/numbers/GearedNumber.vue')['default']
    Hedgehog: typeof import('./src/components/numbers/Hedgehog.vue')['default']
    Item: typeof import('./src/components/items/Item.vue')['default']
    ItemIcon: typeof import('./src/components/items/ItemIcon.vue')['default']
    MCFont: typeof import('./src/components/strings/MCFont.vue')['default']
    MCString: typeof import('./src/components/strings/MCString.vue')['default']
    ModBar: typeof import('./src/components/mods/ModBar.vue')['default']
    PuredValue: typeof import('./src/components/numbers/PuredValue.vue')['default']
    Recipe: typeof import('./src/components/recipes/Recipe.vue')['default']
    Recipes: typeof import('./src/components/recipes/Recipes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}

export {}
