// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseID: typeof import('./src/components/strings/BaseID.vue')['default']
    BigNumber: typeof import('./src/components/numbers/BigNumber.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CRecipe: typeof import('./src/components/recipes/CRecipe.vue')['default']
    CurveText: typeof import('./src/components/CurveText.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmoteNumber: typeof import('./src/components/numbers/EmoteNumber.vue')['default']
    EntryGrid: typeof import('./src/components/items/EntryGrid.vue')['default']
    Footer: typeof import('./src/components/unused/Footer.vue')['default']
    GearedNumber: typeof import('./src/components/numbers/GearedNumber.vue')['default']
    Hedgehog: typeof import('./src/components/numbers/Hedgehog.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemDetailed: typeof import('./src/components/items/ItemDetailed.vue')['default']
    ItemIcon: typeof import('./src/components/items/ItemIcon.vue')['default']
    ItemIconMap: typeof import('./src/components/items/ItemIconMap.vue')['default']
    ItemSimple: typeof import('./src/components/items/ItemSimple.vue')['default']
    MCFont: typeof import('./src/components/strings/MCFont.vue')['default']
    MCString: typeof import('./src/components/strings/MCString.vue')['default']
    ModBar: typeof import('./src/components/mods/ModBar.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PuredValue: typeof import('./src/components/numbers/PuredValue.vue')['default']
    QuestionMark: typeof import('./src/components/QuestionMark.vue')['default']
    Recipes: typeof import('./src/components/recipes/Recipes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}
